# NodeJS Version 16
FROM node:lts-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Change ownership of the application directory
RUN chown -R 1000:1000 /app

RUN apt-get update -y && apt-get install -y openssl

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV development

EXPOSE 3000

# Switch to user 1000
USER 1000

# Cmd script
CMD ["npm", "run", "dev"]
