# NodeJS Version 20
FROM node:20.2.0-alpine

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN yarn install

# Set Env
ENV NODE_ENV development
EXPOSE 3000

# Cmd script
CMD ["npm", "dev"]