tags:
  - name: Users
    description: Users API

paths:
  /api/auth/login:
    post:
      summary: User login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginRequest
          description: User credentials for login
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Successful login
          schema:
            type: object
            properties:
              user:
                $ref: "#/definitions/User"
              accessToken:
                type: string
              refreshToken:
                type: string
              _links:
                type: object
                properties:
                  self:
                    type: object
                    properties:
                      href:
                        type: string
                      method:
                        type: string
                  refreshToken:
                    type: object
                    properties:
                      href:
                        type: string
                      method:
                        type: string
        400:
          description: Bad request (invalid email or password)
        401:
          description: Unauthorized (user not found or incorrect password)
      tags:
        - Authentication
  /api/auth/register:
    post:
      summary: User registration
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: registerRequest
          description: User registration details
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Successful registration
          schema:
            type: object
            properties:
              user:
                $ref: "#/definitions/User"
        400:
          description: Bad request (email already exists)
        500:
          description: Internal server error
      tags:
        - Authentication
  /api/auth/logout:
    post:
      summary: User logout
      produces:
        - application/json
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful logout
          schema:
            type: object
            properties:
              user:
                $ref: "#/definitions/User"
              message:
                type: string
        401:
          description: Unauthorized (invalid or missing access token)
        500:
          description: Internal server error
      tags:
        - Authentication
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      password:
        type: string
      emailVerified:
        type: date
      refreshToken:
        type: string
      accessToken:
        type: string